/* eslint-disable */
// Generated by `npx convex codegen`. Hand-written fallback until a deployment is configured.
import { anyApi } from "convex/server";

export const api: any = anyApi;
export const internal: any = anyApi;
