/* eslint-disable */
// Generated by `npx convex codegen`. Hand-written fallback until a deployment is configured.
export type Id<TableName extends string = string> = string & { __tableName: TableName };
export type Doc<TableName extends string = string> = any & { _id: Id<TableName>; _creationTime: number };
export type DataModel = any;
