/* eslint-disable */
// Generated by `npx convex codegen`. Hand-written fallback until a deployment is configured.
export {
  actionGeneric as action,
  httpActionGeneric as httpAction,
  internalActionGeneric as internalAction,
  internalMutationGeneric as internalMutation,
  internalQueryGeneric as internalQuery,
  mutationGeneric as mutation,
  queryGeneric as query,
} from "convex/server";
import type {
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
} from "convex/server";

export type ActionCtx = GenericActionCtx<any>;
export type MutationCtx = GenericMutationCtx<any>;
export type QueryCtx = GenericQueryCtx<any>;
