// lib/canvas/design-tokens-export.ts
// DesignSystemTokens + taste palette → CSS custom properties + Tailwind theme fragment.

import type { DesignSystemTokens } from "./generate-system";
import type { TasteProfile } from "@/types/taste-profile";
import { defaultDesignTokens } from "@/lib/agent/default-design-tokens";

export type DesignTokensExportInput = {
  tokens?: DesignSystemTokens | null;
  tasteProfile?: TasteProfile | null;
};

function resolvePalette(input: DesignTokensExportInput) {
  const tokens = input.tokens ?? defaultDesignTokens();
  const suggested = input.tasteProfile?.colorBehavior.suggestedColors;

  return {
    background: suggested?.background ?? tokens.colors.background,
    surface: suggested?.surface ?? tokens.colors.surface,
    text: suggested?.text ?? tokens.colors.text,
    textMuted: tokens.colors.textMuted,
    accent: suggested?.accent ?? tokens.colors.accent,
    primary: tokens.colors.primary,
    secondary: suggested?.secondary ?? tokens.colors.secondary,
    border: tokens.colors.border,
  };
}

export function buildTokensCss(input: DesignTokensExportInput = {}): string {
  const tokens = input.tokens ?? defaultDesignTokens();
  const palette = resolvePalette(input);

  const lines = [
    ":root {",
    `  --color-background: ${palette.background};`,
    `  --color-surface: ${palette.surface};`,
    `  --color-text: ${palette.text};`,
    `  --color-text-muted: ${palette.textMuted};`,
    `  --color-accent: ${palette.accent};`,
    `  --color-primary: ${palette.primary};`,
    `  --color-secondary: ${palette.secondary};`,
    `  --color-border: ${palette.border};`,
    `  --font-family: ${tokens.typography.fontFamily};`,
    `  --spacing-unit: ${tokens.spacing.unit}px;`,
    `  --radius-sm: ${tokens.radii.sm};`,
    `  --radius-md: ${tokens.radii.md};`,
    `  --radius-lg: ${tokens.radii.lg};`,
    `  --shadow-md: ${tokens.shadows.md};`,
    "}",
    "",
  ];

  return lines.join("\n");
}

export function buildTailwindTokensJs(input: DesignTokensExportInput = {}): string {
  const tokens = input.tokens ?? defaultDesignTokens();
  const palette = resolvePalette(input);

  const themeExtend = {
    colors: {
      background: palette.background,
      surface: palette.surface,
      foreground: palette.text,
      muted: palette.textMuted,
      accent: palette.accent,
      primary: palette.primary,
      secondary: palette.secondary,
      border: palette.border,
    },
    fontFamily: {
      sans: [tokens.typography.fontFamily],
    },
    borderRadius: {
      sm: tokens.radii.sm,
      md: tokens.radii.md,
      lg: tokens.radii.lg,
    },
    spacing: tokens.spacing.scale,
  };

  return `/** Generated by Studio OS — merge into tailwind.config theme.extend */
module.exports = ${JSON.stringify({ theme: { extend: themeExtend } }, null, 2)};
`;
}
