import type { UnifiedFont } from "./types";

export const fontshareFonts: UnifiedFont[] = [
  { family: "Satoshi", category: "sans-serif", variants: ["Light", "Regular", "Medium", "Bold", "Black"], source: "fontshare", slug: "satoshi" },
  { family: "General Sans", category: "sans-serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "general-sans" },
  { family: "Cabinet Grotesk", category: "sans-serif", variants: ["Regular", "Medium", "Bold", "Extrabold", "Black"], source: "fontshare", slug: "cabinet-grotesk" },
  { family: "Clash Display", category: "display", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "clash-display" },
  { family: "Clash Grotesk", category: "sans-serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "clash-grotesk" },
  { family: "Switzer", category: "sans-serif", variants: ["Light", "Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "switzer" },
  { family: "Zodiak", category: "serif", variants: ["Regular", "Italic", "Bold"], source: "fontshare", slug: "zodiak" },
  { family: "Erode", category: "serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "erode" },
  { family: "Boska", category: "serif", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "boska" },
  { family: "Gambarino", category: "serif", variants: ["Regular"], source: "fontshare", slug: "gambarino" },
  { family: "Nippo", category: "sans-serif", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "nippo" },
  { family: "Panchang", category: "display", variants: ["Regular", "Medium", "Semibold", "Bold", "Extrabold"], source: "fontshare", slug: "panchang" },
  { family: "Chillax", category: "sans-serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "chillax" },
  { family: "Synonym", category: "sans-serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "synonym" },
  { family: "Ranade", category: "sans-serif", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "ranade" },
  { family: "Plein", category: "display", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "plein" },
  { family: "Sentient", category: "serif", variants: ["Regular", "Italic", "Bold"], source: "fontshare", slug: "sentient" },
  { family: "Melodrama", category: "serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "melodrama" },
  { family: "Archivo", category: "sans-serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "archivo" },
  { family: "Jet Brains Mono", category: "monospace", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "jet-brains-mono" },
  { family: "Author", category: "sans-serif", variants: ["Regular", "Medium", "Semibold", "Bold"], source: "fontshare", slug: "author" },
  { family: "Bespoke Serif", category: "serif", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "bespoke-serif" },
  { family: "Bespoke Sans", category: "sans-serif", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "bespoke-sans" },
  { family: "Bespoke Stencil", category: "display", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "bespoke-stencil" },
  { family: "Tanker", category: "display", variants: ["Regular"], source: "fontshare", slug: "tanker" },
  { family: "Bonny", category: "serif", variants: ["Regular", "Italic", "Bold"], source: "fontshare", slug: "bonny" },
  { family: "Alpino", category: "sans-serif", variants: ["Regular", "Medium", "Bold"], source: "fontshare", slug: "alpino" },
  { family: "Supreme", category: "sans-serif", variants: ["Regular", "Medium", "Bold", "Extrabold"], source: "fontshare", slug: "supreme" },
  { family: "Array", category: "display", variants: ["Regular", "Italic"], source: "fontshare", slug: "array" },
  { family: "Stardom", category: "display", variants: ["Regular"], source: "fontshare", slug: "stardom" },
];
